server:
  port: 8094
  tomcat:
    max-http-post-size: 4096
  ssl:
    key-store: classpath:1015011_www.wakeupeidolon.cn.pfx
    key-store-password: Eu57tXRA
    key-store-type: PKCS12

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.74.47:3306/db_comment_label?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Wang123
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 28000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      validation-query-timeout: 10

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

logging:
  path: /home/comment-label/log/

config:
  https-port: 8095
  async:
    executor:
      core-pool-size: 10
      max-pool-size: 200
      queue-capacity: 20
      keep-alive: 60
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 30000
    pool:
      max-idle: 8
      min-idle: 0
      max-wait-millis: 10000
      max-active: 100
